language: python
python:
  - "2.7"
  - "3.3"
env:
  - BENBEN_TEST_DB_STRING=postgresql://postgres@localhost:5432/benben_testing
  - BENBEN_TEST_DB_STRING=sqlite://
install:
  - pip install -e . -r requirements.txt
  - python setup.py dev
  - pip install psycopg2
before_script:
  - psql -c 'create database benben_testing;' -U postgres
script: py.test --tb=native --cov=benben --cov-report=term-missing
